Function

In [1]:
x = 1
y = 2 
x + y

3

In [2]:
x

1

In [3]:
def add(x, y):
    return x + y

add(1,2)

3

In [6]:
def add_num(x,y,z=None):
    if (z == None):
        return x + y
    else:
        return x + y + z

print(add_num(1,2))
print(add_num(1,2,3))

3
6


In [7]:
def add_num(x,y,z=None, flag=False):
    if (flag):
        print('Flag is true')
    if (z == None):
        return x + y
    else:
        return x + y + z
print(add_num(1,2,flag=True))

Flag is true
3


In [8]:
def add(x, y):
    return x + y

a = add
a(1,2)

3

In [10]:
def do_math(a, b, kind='add'):
  if (kind =='add'):
    return a+b
  else:
    return a-b

do_math(1, 2)

3

Python Types and Sequences

In [11]:
type("This is a string")

str

In [12]:
type(None)

NoneType

In [13]:
type(1)

int

In [14]:
type(add_num)

function

In [15]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [16]:
x =[1, 'a', 2, 'b']
type(x)

list

In [17]:
x.append(3.3)
x

[1, 'a', 2, 'b', 3.3]

In [18]:
for item in x:
    print(item)

1
a
2
b
3.3


In [21]:
i = 0
while( i != len(x)):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


In [22]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [23]:
[3] * 3

[3, 3, 3]

In [24]:
1 in [1,2,3]

True

In [25]:
4 in [1,2,3]

False

In [30]:
x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])
print(x[10:])
print(x[:10])
print(x[-5:-2])

T
T
Th
string
This is a 
tri


In [31]:
x = 'Dr. Christopher Brooks'

print(x[3:-6])

 Christopher 


In [35]:
x = 'Dr. Christopher Brooks'

print(x[4:15], x[4:9])


Christopher Chris


In [37]:
firstname = 'Khalid'
lastname = 'Alghamdi'

print(firstname + ' ' + lastname)
print(firstname * 3)
print('K' in firstname)

Khalid Alghamdi
KhalidKhalidKhalid
True


In [39]:
firstname = 'Khalid Mohammed Ahmed Alghamdi'.split(' ')[0]
lastname = 'Khalid Mohammed Ahmed Alghamdi'.split(' ')[-1]

print(firstname + lastname)

KhalidAlghamdi


In [41]:
"Khalid" + str(4)

'Khalid4'

In [42]:
x = {'Khalid': 'khaid@khalid', 'koko': 'koko@khoko'}
x['Khalid']

'khaid@khalid'

In [45]:
for rr in x:
    print(x[rr])

khaid@khalid
koko@khoko


In [46]:
for email in x.values():
    print(email)

khaid@khalid
koko@khoko


In [47]:
for name, email in x.items():
    print(name)
    print(email)

Khalid
khaid@khalid
koko
koko@khoko


In [49]:
sales_recoed = {
    'price': 33,
    'num_items': 10,
    'person': 'Khalid'
}

sales_statemnt = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statemnt.format(
    sales_recoed['person'],
    sales_recoed['num_items'],
    sales_recoed['price'],
    sales_recoed['num_items']*sales_recoed['price']
))

Khalid bought 10 item(s) at a price of 33 each for a total of 330


Data Files and Summary statistics

In [52]:
import csv

%precision 2

with open('./data/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [53]:
len(mpg)

234

In [55]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [56]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [57]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [59]:
# Here, set function returns to us the unique d['cyl'] numbers in our list of dictionaries which correspond to the uniqe cylinder levels.
cylinders = set (d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [63]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [65]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass


HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the vehicle type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

Advanced Python Objects, map()

In [68]:
class Person:
    dept = 'SABIC'

    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location


In [69]:
person = Person()
person.set_name('Khalid Alghamdi')
person.set_location("Ryiadh")
print('{} live in {} and works in {}'.format(person.name, person.location, person.dept))

Khalid Alghamdi live in Ryiadh and works in SABIC


In [71]:
store1 = [10.00, 11.00, 10.44, 13.00]
store2 = [10.00, 15.00, 13.44, 13.33]
ch = map(min, store1, store2)
ch

In [73]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

Advanced Python Lambda and List Comprehensions

In [79]:
my_fun = lambda a, b, c : a + b

In [80]:
my_fun(22,33,44)

55

In [84]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [86]:
my_list = []
for num in range(0,10):
    if num % 2 == 0:
        my_list.append(num)
my_list

[0, 2, 4, 6, 8]

In [89]:
my_list = [num for num in range(1,10) if num %  2 == 0]
my_list

[2, 4, 6, 8]

In [90]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [  lambda i,j : i*j]


False

In [91]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

In [92]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = []
correct_answer == answer

NameError: name 'correct_answer' is not defined

In [93]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

Numerical Python Library (NumPy)

In [94]:
import numpy as np
import math

In [97]:
a = np.array([1,2,3])

print(a)
# Number of dimensions
print(a.ndim)

[1 2 3]
1


In [98]:
b = np.array([[123, 321,222], [333,444,555]])
print(b)
print(b.shape)
print(b.dtype)

[[123 321 222]
 [333 444 555]]
(2, 3)
int32


In [99]:
f = np.arange(10,50,5)
f

array([10, 15, 20, 25, 30, 35, 40, 45])

In [100]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [104]:
farenheit = np.array([0,-10,20,-30,0,100])

# (F - 32) X 5/9
celcius = (farenheit - 32) * (5/9)
celcius

array([-17.77777778, -23.33333333,  -6.66666667, -34.44444444,
       -17.77777778,  37.77777778])

In [105]:
celcius > -20

array([ True, False,  True, False,  True,  True])

In [106]:
celcius%2 == 0

array([False, False, False, False, False, False])

In [107]:
A = np.array([[1,2], [3, 4]])
B = np.array([[3,5], [9, 7]])
print(A*B)
print(A@B)

[[ 3 10]
 [27 28]]
[[21 19]
 [45 43]]


Manipulating Text with Regular Expression


In [111]:
import re

In [113]:
text = 'This is a good day.'

if re.search('good', text):
    print('Wonderful')
else:
    print('Bad')

Wonderful


In [121]:
text = "Khalid is good. Khalid is bad. Khalid is okay. Khalid is sleeping."

re.split("Khalid", text)

['', ' is good. ', ' is bad. ', ' is okay. ', ' is sleeping.']

In [126]:
re.findall("Khalid", text)

['Khalid', 'Khalid', 'Khalid', 'Khalid']

In [129]:
text = "Khalid is good. Khalid is bad. Khalid is okay. Khalid is sleeping."
re.search("^Khalid", text)

<re.Match object; span=(0, 6), match='Khalid'>

Patterns and Character classes

In [146]:
grades= "AABBAACCABCACB"

# How Many C
print(re.findall("C", grades), 'How Many C')
print('-------------')
# Count A's or B's
print(re.findall("[AB]", grades), 'Count A or B')
print('-------------')
# Regex
print(re.findall("[A][B-C]", grades), 'Regex')
print('-------------')
# [AB] pattern
print(re.findall("AB|AC", grades), '[AB] pattern')
print('-------------')
# Negate the grades
print(re.findall("[^A]", grades), 'Negate the grades A')
print('-------------')
# If A match at the beginning
print(re.findall("^[^A]", grades), 'A match at the beginning') 


['C', 'C', 'C', 'C'] How Many C
-------------
['A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'B'] Count A or B
-------------
['AB', 'AC', 'AB', 'AC'] Regex
-------------
['AB', 'AC', 'AB', 'AC'] [AB] pattern
-------------
['B', 'B', 'C', 'C', 'B', 'C', 'C', 'B'] Negate the grades A
-------------
[] A match at the beginning
